spring.application.name=journalApp

# Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/journalApp

# PostgreSQL username
spring.datasource.username=postgres

# PostgreSQL password
spring.datasource.password=Saini@0000

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# Show SQL Queries
spring.jpa.show-sql=true

